#pragma once
#include<vtkSmartPointer.h>
#include<vtkStringArray.h>
#include<vtkJPEGReader.h>
#include<vtkImageViewer2.h>
#include<vtkStdString.h>
#include<vtkBMPReader.h>
#include<vtkVolume.h>
#include<vtkRenderer.h>
#include<vtkRenderWindow.h>
#include<vtkRenderWindowInteractor.h>
#include<vtkImageAppend.h>
#include<vtkVolumeRayCastMapper.h>
#include<vtkVolumeRayCastCompositeFunction.h>
#include<vtkVolumeProperty.h>
#include<vtkImageCast.h>
#include<vtkImageActor.h>
#include<vtkImageData.h>
#include<vtkPiecewiseFunction.h>
#include<vtkColorTransferFunction.h>
#include<vtkImageLuminance.h>
#include<vtkInteractorStyleTrackballCamera.h>
#include<vtkSphereSource.h>
#include<vtkPolyDataMapper.h>
#include<vtkPicker.h>
#include<vtkPointPicker.h>
#include<vtkProperty.h>
#include<vtkRendererCollection.h>
#include<vtkDataSetMapper.h>
#include<vtkCellPicker.h>
#include<vtkIdTypeArray.h>
#include<vtkSelection.h>
#include<vtkExtractSelection.h>
#include<vtkSelectionNode.h>
#include<vtkActor.h>
#include<vtkVolumeRayCastMapper.h>
#include<vtkVolumeRayCastMIPFunction.h>
#include<iostream>
#include<vtkPlaneSource.h>
#include<vtkPolyDataMapper.h>
#include<vtkCamera.h>
#include<vtkLineSource.h>
#include<vtkStringArray.h>
#include<vtkAutoInit.h>
#include<vtkRayCastImageDisplayHelper.h>